server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dia101/RKSP_final_practice.git
          clone-on-start: true
          default-label: main
          search-paths:
            - '/services/config-server/src/main/resources/configurations/'